<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Topic 5 EDA for Feature Engineering | STA551 E-Pack: Foundations of Data Science</title>
  <meta name="description" content="The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="Topic 5 EDA for Feature Engineering | STA551 E-Pack: Foundations of Data Science" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/STA551EB" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Topic 5 EDA for Feature Engineering | STA551 E-Pack: Foundations of Data Science" />
  
  <meta name="twitter:description" content="The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Cheng Peng" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="exploratory-data-analysis-eda.html"/>
<link rel="next" href="multiple-linear-regression.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<center><li><a href="./"><font color = "darkred"><b>STA 551 E-Pack: Foundations of Data Science</b></font></a><br><font color = "navy">Cheng Peng</font></li></center>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#the-origin-of-data-science"><i class="fa fa-check"></i><b>1.1</b> The Origin of Data Science</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#the-coverage-of-the-first-data-science-course"><i class="fa fa-check"></i><b>1.2</b> The Coverage of the First Data Science Course</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#tentative-topics"><i class="fa fa-check"></i><b>1.3</b> Tentative Topics</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-science---a-big-picture.html"><a href="data-science---a-big-picture.html"><i class="fa fa-check"></i><b>2</b> Data Science - A Big Picture</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-science---a-big-picture.html"><a href="data-science---a-big-picture.html#data-science-process"><i class="fa fa-check"></i><b>2.1</b> Data Science Process</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="data-science---a-big-picture.html"><a href="data-science---a-big-picture.html#what-is-data"><i class="fa fa-check"></i><b>2.1.1</b> What is Data?</a></li>
<li class="chapter" data-level="2.1.2" data-path="data-science---a-big-picture.html"><a href="data-science---a-big-picture.html#data-storage-and-retrieval"><i class="fa fa-check"></i><b>2.1.2</b> Data Storage and Retrieval</a></li>
<li class="chapter" data-level="2.1.3" data-path="data-science---a-big-picture.html"><a href="data-science---a-big-picture.html#different-da-roles-in-industry"><i class="fa fa-check"></i><b>2.1.3</b> Different DA Roles in Industry</a></li>
<li class="chapter" data-level="2.1.4" data-path="data-science---a-big-picture.html"><a href="data-science---a-big-picture.html#cloud-computing"><i class="fa fa-check"></i><b>2.1.4</b> Cloud Computing</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="data-science---a-big-picture.html"><a href="data-science---a-big-picture.html#from-business-questions-to-analytic-question"><i class="fa fa-check"></i><b>2.2</b> From Business Questions to Analytic Question</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="data-science---a-big-picture.html"><a href="data-science---a-big-picture.html#business-goal"><i class="fa fa-check"></i><b>2.2.1</b> Business Goal</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-science---a-big-picture.html"><a href="data-science---a-big-picture.html#analytic-question"><i class="fa fa-check"></i><b>2.2.2</b> Analytic Question</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-science---a-big-picture.html"><a href="data-science---a-big-picture.html#concepts-of-relational-databases-and-sql"><i class="fa fa-check"></i><b>2.3</b> Concepts of Relational Databases and SQL</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="data-science---a-big-picture.html"><a href="data-science---a-big-picture.html#what-is-database"><i class="fa fa-check"></i><b>2.3.1</b> What is Database?</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-science---a-big-picture.html"><a href="data-science---a-big-picture.html#what-is-a-data-warehouse"><i class="fa fa-check"></i><b>2.3.2</b> What is a Data Warehouse?</a></li>
<li class="chapter" data-level="2.3.3" data-path="data-science---a-big-picture.html"><a href="data-science---a-big-picture.html#difference-between-database-and-data-warehouse"><i class="fa fa-check"></i><b>2.3.3</b> Difference between Database and Data Warehouse</a></li>
<li class="chapter" data-level="2.3.4" data-path="data-science---a-big-picture.html"><a href="data-science---a-big-picture.html#database-management-system-dbms"><i class="fa fa-check"></i><b>2.3.4</b> Database Management System (DBMS)</a></li>
<li class="chapter" data-level="2.3.5" data-path="data-science---a-big-picture.html"><a href="data-science---a-big-picture.html#some-definitions-and-notations-of-relational-tables"><i class="fa fa-check"></i><b>2.3.5</b> Some Definitions and Notations of Relational Tables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="running-sql-in-sas-and-r.html"><a href="running-sql-in-sas-and-r.html"><i class="fa fa-check"></i><b>3</b> Running SQL in SAS and R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="running-sql-in-sas-and-r.html"><a href="running-sql-in-sas-and-r.html#running-sql-in-sas"><i class="fa fa-check"></i><b>3.1</b> Running SQL in SAS</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="running-sql-in-sas-and-r.html"><a href="running-sql-in-sas-and-r.html#loading-data"><i class="fa fa-check"></i><b>3.1.1</b> Loading Data</a></li>
<li class="chapter" data-level="3.1.2" data-path="running-sql-in-sas-and-r.html"><a href="running-sql-in-sas-and-r.html#basic-sql-syntax-and-clauses"><i class="fa fa-check"></i><b>3.1.2</b> Basic SQL Syntax and Clauses</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="running-sql-in-sas-and-r.html"><a href="running-sql-in-sas-and-r.html#running-sas-in-r"><i class="fa fa-check"></i><b>3.2</b> Running SAS in R</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="running-sql-in-sas-and-r.html"><a href="running-sql-in-sas-and-r.html#connect-r-to-existing-database"><i class="fa fa-check"></i><b>3.2.1</b> Connect R to Existing Database</a></li>
<li class="chapter" data-level="3.2.2" data-path="running-sql-in-sas-and-r.html"><a href="running-sql-in-sas-and-r.html#create-sqlite-database-with-r"><i class="fa fa-check"></i><b>3.2.2</b> Create SQLite Database with R</a></li>
<li class="chapter" data-level="3.2.3" data-path="running-sql-in-sas-and-r.html"><a href="running-sql-in-sas-and-r.html#running-sql-queries-in-r-code-chunks"><i class="fa fa-check"></i><b>3.2.3</b> Running SQL Queries in R Code chunks</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html"><i class="fa fa-check"></i><b>4</b> Exploratory Data Analysis (EDA)</a>
<ul>
<li class="chapter" data-level="4.1" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#tools-of-eda-and-applications"><i class="fa fa-check"></i><b>4.1</b> Tools of EDA and Applications</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#descriptive-statistics-approach"><i class="fa fa-check"></i><b>4.1.1</b> Descriptive Statistics Approach</a></li>
<li class="chapter" data-level="4.1.2" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#graphical-approach"><i class="fa fa-check"></i><b>4.1.2</b> Graphical Approach</a></li>
<li class="chapter" data-level="4.1.3" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#algorithm-based-method"><i class="fa fa-check"></i><b>4.1.3</b> Algorithm-based Method</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#visual-techniques-of-eda"><i class="fa fa-check"></i><b>4.2</b> Visual Techniques of EDA</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#univariate-eda"><i class="fa fa-check"></i><b>4.2.1</b> Univariate EDA</a></li>
<li class="chapter" data-level="4.2.2" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#two-variables"><i class="fa fa-check"></i><b>4.2.2</b> Two Variables</a></li>
<li class="chapter" data-level="4.2.3" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#three-or-more-variables"><i class="fa fa-check"></i><b>4.2.3</b> Three or More Variables</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#roles-of-visualization-in-eda"><i class="fa fa-check"></i><b>4.3</b> Roles of Visualization in EDA</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#data-visualization"><i class="fa fa-check"></i><b>4.3.1</b> Data Visualization</a></li>
<li class="chapter" data-level="4.3.2" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#visual-analytics"><i class="fa fa-check"></i><b>4.3.2</b> Visual Analytics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="eda-for-feature-engineering.html"><a href="eda-for-feature-engineering.html"><i class="fa fa-check"></i><b>5</b> EDA for Feature Engineering</a>
<ul>
<li class="chapter" data-level="5.1" data-path="eda-for-feature-engineering.html"><a href="eda-for-feature-engineering.html#description-of-data"><i class="fa fa-check"></i><b>5.1</b> Description of Data</a></li>
<li class="chapter" data-level="5.2" data-path="eda-for-feature-engineering.html"><a href="eda-for-feature-engineering.html#eda-for-feature-engineering-1"><i class="fa fa-check"></i><b>5.2</b> EDA for Feature Engineering</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="eda-for-feature-engineering.html"><a href="eda-for-feature-engineering.html#missing-values---imputation"><i class="fa fa-check"></i><b>5.2.1</b> Missing Values - Imputation</a></li>
<li class="chapter" data-level="5.2.2" data-path="eda-for-feature-engineering.html"><a href="eda-for-feature-engineering.html#assess-distributions"><i class="fa fa-check"></i><b>5.2.2</b> Assess Distributions</a></li>
<li class="chapter" data-level="5.2.3" data-path="eda-for-feature-engineering.html"><a href="eda-for-feature-engineering.html#pairwise-association"><i class="fa fa-check"></i><b>5.2.3</b> Pairwise Association</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="eda-for-feature-engineering.html"><a href="eda-for-feature-engineering.html#concluding-remarks"><i class="fa fa-check"></i><b>5.3</b> Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>6</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="6.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#the-practical-question"><i class="fa fa-check"></i><b>6.1</b> The Practical Question</a></li>
<li class="chapter" data-level="6.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#the-process-of-building-a-multiple-linear-regression-model"><i class="fa fa-check"></i><b>6.2</b> The Process of Building A Multiple Linear Regression Model</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#assumptions-of-mlr"><i class="fa fa-check"></i><b>6.2.1</b> Assumptions of MLR</a></li>
<li class="chapter" data-level="6.2.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#the-structure-of-mlr"><i class="fa fa-check"></i><b>6.2.2</b> The Structure of MLR</a></li>
<li class="chapter" data-level="6.2.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#more-on-model-specifications"><i class="fa fa-check"></i><b>6.2.3</b> More on Model Specifications</a></li>
<li class="chapter" data-level="6.2.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#estimation-of-regression-coefficients"><i class="fa fa-check"></i><b>6.2.4</b> Estimation of Regression Coefficients</a></li>
<li class="chapter" data-level="6.2.5" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#model-diagnostics"><i class="fa fa-check"></i><b>6.2.5</b> Model Diagnostics</a></li>
<li class="chapter" data-level="6.2.6" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#goodness-of-fit-and-variable-selection"><i class="fa fa-check"></i><b>6.2.6</b> Goodness-of-fit and Variable Selection</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#case-study-1"><i class="fa fa-check"></i><b>6.3</b> Case Study 1</a></li>
<li class="chapter" data-level="6.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#case-study-2"><i class="fa fa-check"></i><b>6.4</b> Case Study 2</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html"><i class="fa fa-check"></i><b>7</b> Logistic Regression Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#motivational-example-and-practical-question"><i class="fa fa-check"></i><b>7.1</b> Motivational Example and Practical Question</a></li>
<li class="chapter" data-level="7.2" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#logistic-regression-models-and-applications"><i class="fa fa-check"></i><b>7.2</b> Logistic Regression Models and Applications</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#the-structure-of-the-logistic-regression-model"><i class="fa fa-check"></i><b>7.2.1</b> The Structure of the Logistic Regression Model</a></li>
<li class="chapter" data-level="7.2.2" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#assumptions-and-diagnostics"><i class="fa fa-check"></i><b>7.2.2</b> Assumptions and Diagnostics</a></li>
<li class="chapter" data-level="7.2.3" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#coefficient-estimation-and-interpretation"><i class="fa fa-check"></i><b>7.2.3</b> Coefficient Estimation and Interpretation</a></li>
<li class="chapter" data-level="7.2.4" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#use-of-glm-and-annotations"><i class="fa fa-check"></i><b>7.2.4</b> Use of <strong>glm()</strong> and Annotations</a></li>
<li class="chapter" data-level="7.2.5" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#applications-of-logistic-regression-models"><i class="fa fa-check"></i><b>7.2.5</b> Applications of Logistic Regression Models</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#case-studies"><i class="fa fa-check"></i><b>7.3</b> Case Studies</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#the-simple-logistic-regression-model"><i class="fa fa-check"></i><b>7.3.1</b> The simple logistic regression model</a></li>
<li class="chapter" data-level="7.3.2" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#multiple-logistic-regression-model"><i class="fa fa-check"></i><b>7.3.2</b> Multiple Logistic Regression Model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="basics-of-bootstrap-method.html"><a href="basics-of-bootstrap-method.html"><i class="fa fa-check"></i><b>8</b> Basics of Bootstrap Method</a>
<ul>
<li class="chapter" data-level="8.1" data-path="basics-of-bootstrap-method.html"><a href="basics-of-bootstrap-method.html#basic-idea-of-bootstrap-method."><i class="fa fa-check"></i><b>8.1</b> Basic Idea of Bootstrap Method.</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="basics-of-bootstrap-method.html"><a href="basics-of-bootstrap-method.html#random-sample-from-population"><i class="fa fa-check"></i><b>8.1.1</b> Random Sample from Population</a></li>
<li class="chapter" data-level="8.1.2" data-path="basics-of-bootstrap-method.html"><a href="basics-of-bootstrap-method.html#bootstrap-sampling-and-bootstrap-sampling-distribution"><i class="fa fa-check"></i><b>8.1.2</b> Bootstrap Sampling and Bootstrap Sampling Distribution</a></li>
<li class="chapter" data-level="8.1.3" data-path="basics-of-bootstrap-method.html"><a href="basics-of-bootstrap-method.html#relationship-between-two-estimated-sampling-distributions"><i class="fa fa-check"></i><b>8.1.3</b> Relationship between Two Estimated Sampling Distributions</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="basics-of-bootstrap-method.html"><a href="basics-of-bootstrap-method.html#bootstrap-confidence-intervals"><i class="fa fa-check"></i><b>8.2</b> Bootstrap Confidence Intervals</a></li>
<li class="chapter" data-level="8.3" data-path="basics-of-bootstrap-method.html"><a href="basics-of-bootstrap-method.html#bootstrap-confidence-interval-of-correlation-coefficient"><i class="fa fa-check"></i><b>8.3</b> Bootstrap Confidence Interval of Correlation Coefficient</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="basics-of-bootstrap-method.html"><a href="basics-of-bootstrap-method.html#bootstrapping-data-set"><i class="fa fa-check"></i><b>8.3.1</b> Bootstrapping Data Set</a></li>
<li class="chapter" data-level="8.3.2" data-path="basics-of-bootstrap-method.html"><a href="basics-of-bootstrap-method.html#confidence-interval-of-coefficient-correlation"><i class="fa fa-check"></i><b>8.3.2</b> Confidence Interval of Coefficient Correlation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html"><i class="fa fa-check"></i><b>9</b> Method of Cross-Validation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#regression-models"><i class="fa fa-check"></i><b>9.1</b> Regression Models</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#linear-regression-model"><i class="fa fa-check"></i><b>9.1.1</b> Linear Regression Model</a></li>
<li class="chapter" data-level="9.1.2" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#logistic-regression-model"><i class="fa fa-check"></i><b>9.1.2</b> Logistic Regression Model</a></li>
<li class="chapter" data-level="9.1.3" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#inference-about-association-and-prediction"><i class="fa fa-check"></i><b>9.1.3</b> Inference about Association and Prediction</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#data-splitting-methods"><i class="fa fa-check"></i><b>9.2</b> Data Splitting Methods</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#training-data"><i class="fa fa-check"></i><b>9.2.1</b> Training Data</a></li>
<li class="chapter" data-level="9.2.2" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#validation-data"><i class="fa fa-check"></i><b>9.2.2</b> Validation Data</a></li>
<li class="chapter" data-level="9.2.3" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#test-data"><i class="fa fa-check"></i><b>9.2.3</b> Test data</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#cross-validation"><i class="fa fa-check"></i><b>9.3</b> Cross-validation</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#k-fold-cross-validation"><i class="fa fa-check"></i><b>9.3.1</b> K-fold Cross-validation</a></li>
<li class="chapter" data-level="9.3.2" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#other-cross-validation-methods"><i class="fa fa-check"></i><b>9.3.2</b> Other Cross-Validation Methods</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#case-study-using-fraud-data"><i class="fa fa-check"></i><b>9.4</b> Case Study Using Fraud Data</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#data-partition"><i class="fa fa-check"></i><b>9.4.1</b> Data Partition</a></li>
<li class="chapter" data-level="9.4.2" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#finding-optimal-cut-off-probability"><i class="fa fa-check"></i><b>9.4.2</b> Finding Optimal Cut-off Probability</a></li>
<li class="chapter" data-level="9.4.3" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#reporting-test"><i class="fa fa-check"></i><b>9.4.3</b> Reporting Test</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="method-of-cross-validation.html"><a href="method-of-cross-validation.html#concluding-remarks-1"><i class="fa fa-check"></i><b>9.5</b> Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="perfomance-measures-of-algorithms-and-models.html"><a href="perfomance-measures-of-algorithms-and-models.html"><i class="fa fa-check"></i><b>10</b> Perfomance Measures of Algorithms and Models</a></li>
<li class="chapter" data-level="11" data-path="classification-performance-metrics.html"><a href="classification-performance-metrics.html"><i class="fa fa-check"></i><b>11</b> Classification Performance Metrics</a>
<ul>
<li class="chapter" data-level="11.1" data-path="classification-performance-metrics.html"><a href="classification-performance-metrics.html#confusion-matrix-for-binary-decision"><i class="fa fa-check"></i><b>11.1</b> Confusion Matrix for Binary Decision</a></li>
<li class="chapter" data-level="11.2" data-path="classification-performance-metrics.html"><a href="classification-performance-metrics.html#local-performance-measures-for-model-development"><i class="fa fa-check"></i><b>11.2</b> Local Performance Measures (for Model Development)</a></li>
<li class="chapter" data-level="11.3" data-path="classification-performance-metrics.html"><a href="classification-performance-metrics.html#global-performance-measures"><i class="fa fa-check"></i><b>11.3</b> Global Performance Measures</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="case-study---logistic-regression-model-with-the-fraud-data.html"><a href="case-study---logistic-regression-model-with-the-fraud-data.html"><i class="fa fa-check"></i><b>12</b> Case Study - Logistic regression model with the fraud data</a>
<ul>
<li class="chapter" data-level="12.1" data-path="case-study---logistic-regression-model-with-the-fraud-data.html"><a href="case-study---logistic-regression-model-with-the-fraud-data.html#local-performance-meaures"><i class="fa fa-check"></i><b>12.1</b> Local Performance Meaures</a></li>
<li class="chapter" data-level="12.2" data-path="case-study---logistic-regression-model-with-the-fraud-data.html"><a href="case-study---logistic-regression-model-with-the-fraud-data.html#global-measure-roc-and-auc"><i class="fa fa-check"></i><b>12.2</b> Global Measure: ROC and AUC</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html"><i class="fa fa-check"></i><b>13</b> From Statistics Models to Machine Learning Algorithms</a>
<ul>
<li class="chapter" data-level="13.1" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#some-technical-terms-and-ml-types"><i class="fa fa-check"></i><b>13.1</b> Some Technical Terms and ML Types</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#machine-learning-problems-and-jargon"><i class="fa fa-check"></i><b>13.1.1</b> Machine Learning Problems and Jargon</a></li>
<li class="chapter" data-level="13.1.2" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#types-of-machine-learning-problems"><i class="fa fa-check"></i><b>13.1.2</b> Types of Machine Learning Problems</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#categories-of-machine-learning"><i class="fa fa-check"></i><b>13.2</b> Categories of Machine Learning</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#supervised-learning"><i class="fa fa-check"></i><b>13.2.1</b> Supervised Learning</a></li>
<li class="chapter" data-level="13.2.2" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#unsupervised-learning"><i class="fa fa-check"></i><b>13.2.2</b> Unsupervised Learning</a></li>
<li class="chapter" data-level="13.2.3" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#semi-supervised-learning"><i class="fa fa-check"></i><b>13.2.3</b> Semi-Supervised Learning</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#from-statistics-to-machine-learning"><i class="fa fa-check"></i><b>13.3</b> From Statistics to Machine Learning</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#logistic-regression-model-revisited"><i class="fa fa-check"></i><b>13.3.1</b> Logistic Regression Model Revisited</a></li>
<li class="chapter" data-level="13.3.2" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#single-layer-neural-network---perceptron"><i class="fa fa-check"></i><b>13.3.2</b> Single Layer Neural Network - Perceptron</a></li>
<li class="chapter" data-level="13.3.3" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#multi-layer-perceptron"><i class="fa fa-check"></i><b>13.3.3</b> Multi-layer Perceptron</a></li>
<li class="chapter" data-level="13.3.4" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#commonly-used-activation-functions"><i class="fa fa-check"></i><b>13.3.4</b> Commonly Used Activation Functions</a></li>
<li class="chapter" data-level="13.3.5" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#algorithms-for-estimating-weights"><i class="fa fa-check"></i><b>13.3.5</b> Algorithms for Estimating Weights</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#implementing-nn-with-r"><i class="fa fa-check"></i><b>13.4</b> Implementing NN with R</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#syntax-of-neuralnet"><i class="fa fa-check"></i><b>13.4.1</b> Syntax of <code>neuralnet</code></a></li>
<li class="chapter" data-level="13.4.2" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#feature-conversion-for-neuralnet"><i class="fa fa-check"></i><b>13.4.2</b> Feature Conversion for <code>neuralnet</code></a></li>
<li class="chapter" data-level="13.4.3" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#numeric-feature-scaling"><i class="fa fa-check"></i><b>13.4.3</b> Numeric Feature Scaling</a></li>
<li class="chapter" data-level="13.4.4" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#extract-all-feature-names"><i class="fa fa-check"></i><b>13.4.4</b> Extract All Feature Names</a></li>
<li class="chapter" data-level="13.4.5" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#define-model-formula"><i class="fa fa-check"></i><b>13.4.5</b> Define Model Formula</a></li>
<li class="chapter" data-level="13.4.6" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#training-and-testing-nn-model"><i class="fa fa-check"></i><b>13.4.6</b> Training and Testing NN Model</a></li>
<li class="chapter" data-level="13.4.7" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#about-deep-learning"><i class="fa fa-check"></i><b>13.4.7</b> About Deep Learning</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="from-statistics-models-to-machine-learning-algorithms.html"><a href="from-statistics-models-to-machine-learning-algorithms.html#clustering-algorithms"><i class="fa fa-check"></i><b>13.5</b> Clustering Algorithms</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STA551 E-Pack: Foundations of Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="eda-for-feature-engineering" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Topic 5</span> EDA for Feature Engineering<a href="eda-for-feature-engineering.html#eda-for-feature-engineering" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Recall the following workflow of the data science project.</p>
<p><img src="img03/DS-project-workflow.png" width="80%" style="display: block; margin: auto;" /></p>
<p>We have introduced the techniques and tools for exploratory data analysis. This note provides an example to show how to use EDA based on the data set used in the example.</p>
<div id="description-of-data" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Description of Data<a href="eda-for-feature-engineering.html#description-of-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A population of women who were at least 21 years old, of Pima Indian heritage, and living near Phoenix, Arizona, was tested for diabetes according to World Health Organization criteria. The data were collected by the US National Institute of Diabetes and Digestive and Kidney. The objective of the data set is to diagnostically predict whether or not a patient has diabetes, based on certain diagnostic measurements included in the data set. Several constraints were placed on the selection of these instances from a larger database.</p>
<p>There are two versions of the data available in the public domain. This case study uses the version that contains the missing values. The total number of records in this data set is 768. The data set consists of 9 variables including the response variable with the name <code>diabetes</code>. Predictor variables include the number of pregnancies the patient has had, their BMI, insulin level, age, and so on. A detailed description of the variables is given below</p>
<p><code>pregnant</code>: Number of times pregnant</p>
<p><code>glucose</code>: Plasma glucose concentration 2 hours in an oral glucose tolerance test</p>
<p><code>pressure</code>: Diastolic blood pressure (mm Hg)</p>
<p><code>triceps</code>: Triceps skin fold thickness (mm)</p>
<p><code>insulin</code>: 2-Hour serum insulin (mu U/ml)</p>
<p><code>mass</code>: Body mass index (weight in kg/(height in m)^2)</p>
<p><code>pedigree</code>: Diabetes pedigree function</p>
<p><code>age</code>: Age (years)</p>
<p><code>diabetes</code>: outcome class variable (‘neg’ or ‘pos’)</p>
<p>A copy of this publicly available data is stored at <a href="https://pengdsci.github.io/datasets/PimaDiabetes/PimaIndiansDiabetes2.csv" class="uri">https://pengdsci.github.io/datasets/PimaDiabetes/PimaIndiansDiabetes2.csv</a>.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="eda-for-feature-engineering.html#cb62-1" tabindex="-1"></a>PimaDiabetes <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;https://pengdsci.github.io/datasets/PimaDiabetes/PimaIndiansDiabetes2.csv&quot;</span>)[, <span class="sc">-</span><span class="dv">1</span>]</span></code></pre></div>
<p><br />
</p>
</div>
<div id="eda-for-feature-engineering-1" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> EDA for Feature Engineering<a href="eda-for-feature-engineering.html#eda-for-feature-engineering-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We have introduced several techniques and methods in an earlier note. We will use some EDA techniques and methods as needed for this data and subsequent modeling.</p>
<p>We first scan the entire data set and determine the EDA tools to use for feature engineering.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="eda-for-feature-engineering.html#cb63-1" tabindex="-1"></a><span class="fu">summary</span>(PimaDiabetes)</span></code></pre></div>
<pre><code>##     pregnant         glucose         pressure         triceps         insulin            mass          pedigree     
##  Min.   : 0.000   Min.   : 44.0   Min.   : 24.00   Min.   : 7.00   Min.   : 14.00   Min.   :18.20   Min.   :0.0780  
##  1st Qu.: 1.000   1st Qu.: 99.0   1st Qu.: 64.00   1st Qu.:22.00   1st Qu.: 76.25   1st Qu.:27.50   1st Qu.:0.2437  
##  Median : 3.000   Median :117.0   Median : 72.00   Median :29.00   Median :125.00   Median :32.30   Median :0.3725  
##  Mean   : 3.845   Mean   :121.7   Mean   : 72.41   Mean   :29.15   Mean   :155.55   Mean   :32.46   Mean   :0.4719  
##  3rd Qu.: 6.000   3rd Qu.:141.0   3rd Qu.: 80.00   3rd Qu.:36.00   3rd Qu.:190.00   3rd Qu.:36.60   3rd Qu.:0.6262  
##  Max.   :17.000   Max.   :199.0   Max.   :122.00   Max.   :99.00   Max.   :846.00   Max.   :67.10   Max.   :2.4200  
##                   NA&#39;s   :5       NA&#39;s   :35       NA&#39;s   :227     NA&#39;s   :374      NA&#39;s   :11                      
##       age          diabetes        
##  Min.   :21.00   Length:768        
##  1st Qu.:24.00   Class :character  
##  Median :29.00   Mode  :character  
##  Mean   :33.24                     
##  3rd Qu.:41.00                     
##  Max.   :81.00                     
## </code></pre>
<div id="missing-values---imputation" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Missing Values - Imputation<a href="eda-for-feature-engineering.html#missing-values---imputation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The above summary table indicates that feature variables <code>glucose</code>, <code>pressure</code>, <code>triceps</code>, <code>insulin</code>, and <code>mass</code> have missing values. <code>insulin</code> has nearly 50% missing values. <code>triceps</code> has 227 missing values. The other three variables have a very low percentage of missing values.</p>
<div id="missing-value-vs-no-value" class="section level4 hasAnchor" number="5.2.1.1">
<h4><span class="header-section-number">5.2.1.1</span> Missing Value vs No Value<a href="eda-for-feature-engineering.html#missing-value-vs-no-value" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Missing value means that the information is available but not collected while no value means that the value does not exist.</p>
<p>Replacing the missing values with proxy values (imputation) or deleting them from the data are the ways of handling missing values. Most software programs <em>automatically delete all records with missing components</em> from the data before modeling if the missing value issue is not handled.</p>
<p><code>no-value</code> should be never imputed in the data processing. The ways of handling <code>no value</code> is to either drop all records with <code>no value</code> components or the feature variables that have <code>no values</code>. The former will change the study population and the latter will lead to a loss of information.</p>
<p><br />
</p>
</div>
<div id="glucose-tolerance-glucose-vs-2-hour-serum-insulin-insulin" class="section level4 hasAnchor" number="5.2.1.2">
<h4><span class="header-section-number">5.2.1.2</span> Glucose Tolerance (<code>glucose</code>) vs 2-Hour Serum Insulin (<code>insulin</code>)<a href="eda-for-feature-engineering.html#glucose-tolerance-glucose-vs-2-hour-serum-insulin-insulin" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Both <code>fasting insulin test</code> and <code>glucose tolerance test</code> are used in diabetes diagnosis, therefore, variables <code>glucose</code> and <code>insulin</code> are correlated. Since nearly 50% of patients did not do the insulin test. Therefore, we can use <code>glucose</code> to impute the missing values in <code>insulin</code>. We first look at the correlation between the two variables based on the complete data.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="eda-for-feature-engineering.html#cb65-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb65-2"><a href="eda-for-feature-engineering.html#cb65-2" tabindex="-1"></a><span class="fu">plot</span>(PimaDiabetes<span class="sc">$</span>glucose, PimaDiabetes<span class="sc">$</span>insulin, <span class="at">xlab =</span> <span class="st">&quot;Glucose Level&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Insulin Level&quot;</span>)</span>
<span id="cb65-3"><a href="eda-for-feature-engineering.html#cb65-3" tabindex="-1"></a><span class="fu">plot</span>(PimaDiabetes<span class="sc">$</span>glucose, <span class="fu">log</span>(PimaDiabetes<span class="sc">$</span>insulin), <span class="at">xlab =</span> <span class="st">&quot;Glucose Level&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;log Insulin Level&quot;</span>)</span></code></pre></div>
<p><img src="STA551EB_files/figure-html/unnamed-chunk-51-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The scatter plot shows that the logarithm of the insulin level and the glucose level are highly linearly correlated. We can use this relationship to impute the logarithm of insulin level based on the no-missing glucose level. Since we will use this data set to build predictive models, the logarithm of insulin will be used directly in the subsequent models and algorithms.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="eda-for-feature-engineering.html#cb66-1" tabindex="-1"></a>impute.insulin.lm <span class="ot">=</span> <span class="fu">lm</span>(<span class="fu">log</span>(insulin[<span class="sc">-</span><span class="dv">446</span>]) <span class="sc">~</span> glucose[<span class="sc">-</span><span class="dv">446</span>], <span class="at">data =</span> PimaDiabetes)</span>
<span id="cb66-2"><a href="eda-for-feature-engineering.html#cb66-2" tabindex="-1"></a><span class="fu">summary</span>(impute.insulin.lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(insulin[-446]) ~ glucose[-446], data = PimaDiabetes)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.87469 -0.31478 -0.02521  0.33826  1.55711 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   3.0588150  0.1095012   27.93   &lt;2e-16 ***
## glucose[-446] 0.0143630  0.0008673   16.56   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5269 on 390 degrees of freedom
##   (因为不存在，375个观察量被删除了)
## Multiple R-squared:  0.4129, Adjusted R-squared:  0.4114 
## F-statistic: 274.3 on 1 and 390 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="eda-for-feature-engineering.html#cb68-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb68-2"><a href="eda-for-feature-engineering.html#cb68-2" tabindex="-1"></a><span class="fu">plot</span>(impute.insulin.lm)</span></code></pre></div>
<p><img src="STA551EB_files/figure-html/unnamed-chunk-53-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Next, we use the following linear regression to impute the missing values in <code>insulin</code>.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="eda-for-feature-engineering.html#cb69-1" tabindex="-1"></a>glucose <span class="ot">=</span> PimaDiabetes<span class="sc">$</span>glucose</span>
<span id="cb69-2"><a href="eda-for-feature-engineering.html#cb69-2" tabindex="-1"></a>impute.log.insulin <span class="ot">=</span> <span class="fu">log</span>(PimaDiabetes<span class="sc">$</span>insulin)</span>
<span id="cb69-3"><a href="eda-for-feature-engineering.html#cb69-3" tabindex="-1"></a>n<span class="ot">=</span><span class="fu">length</span>(impute.log.insulin)</span>
<span id="cb69-4"><a href="eda-for-feature-engineering.html#cb69-4" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n){</span>
<span id="cb69-5"><a href="eda-for-feature-engineering.html#cb69-5" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.na</span>(impute.log.insulin[i]) <span class="sc">==</span> <span class="cn">TRUE</span> <span class="sc">&amp;&amp;</span> <span class="fu">is.na</span>(glucose[i]) <span class="sc">==</span> <span class="cn">FALSE</span>) impute.log.insulin[i] <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">coef</span>(impute.insulin.lm)<span class="sc">*</span><span class="fu">c</span>(<span class="dv">1</span>,glucose[i])) <span class="sc">+</span> <span class="fu">sample</span>(<span class="fu">resid</span>(impute.insulin.lm),<span class="dv">1</span>)</span>
<span id="cb69-6"><a href="eda-for-feature-engineering.html#cb69-6" tabindex="-1"></a>}</span></code></pre></div>
<p>Visual comparison of the distribution between the original <code>insulin</code> and the imputed <code>insulin</code>.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="eda-for-feature-engineering.html#cb70-1" tabindex="-1"></a>den.orig.insulin <span class="ot">=</span> <span class="fu">density</span>(<span class="fu">na.omit</span>(<span class="fu">log</span>(PimaDiabetes<span class="sc">$</span>insulin)))</span>
<span id="cb70-2"><a href="eda-for-feature-engineering.html#cb70-2" tabindex="-1"></a>den.impute.insulin <span class="ot">=</span> <span class="fu">density</span>(<span class="fu">na.omit</span>(impute.log.insulin))</span>
<span id="cb70-3"><a href="eda-for-feature-engineering.html#cb70-3" tabindex="-1"></a><span class="fu">plot</span>(den.impute.insulin, <span class="at">xlab=</span><span class="st">&quot;log insulin&quot;</span>, <span class="at">main =</span> <span class="st">&quot;density curve of log of original and imputed insulin&quot;</span>,</span>
<span id="cb70-4"><a href="eda-for-feature-engineering.html#cb70-4" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb70-5"><a href="eda-for-feature-engineering.html#cb70-5" tabindex="-1"></a><span class="fu">lines</span>(den.orig.insulin, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span>
<span id="cb70-6"><a href="eda-for-feature-engineering.html#cb70-6" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="fu">c</span>(<span class="st">&quot;original log insulin&quot;</span>, <span class="st">&quot;inputed log insulin&quot;</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>), <span class="at">lty =</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">cex =</span> <span class="fl">0.9</span>, <span class="at">bty =</span> <span class="st">&quot;n&quot;</span>)</span></code></pre></div>
<p><img src="STA551EB_files/figure-html/unnamed-chunk-55-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The above density curves show that distributions of the imputed log insulin and original log insulin levels are close to each other.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="eda-for-feature-engineering.html#cb71-1" tabindex="-1"></a>PimaDiabetes<span class="sc">$</span>impute.log.insulin <span class="ot">=</span> impute.log.insulin</span></code></pre></div>
<p><br />
</p>
</div>
<div id="triceps-skinfold-thickness-triceps-vs-body-mass-index-mass" class="section level4 hasAnchor" number="5.2.1.3">
<h4><span class="header-section-number">5.2.1.3</span> Triceps Skinfold Thickness (<code>triceps</code>) vs Body Mass Index (<code>mass</code>)<a href="eda-for-feature-engineering.html#triceps-skinfold-thickness-triceps-vs-body-mass-index-mass" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Clinical variables <code>triceps</code> (triceps skin-fold thickness, see the following figure to see how it is measured) and <code>mass</code> (body mass index) are clinically correlated.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-57"></span>
<img src="img03/tricepts.png" alt="Figure 1. Measurement of triceps skinfold using a Lange caliper. With the subject's arm in a relaxed position, the skinfold is picked with thumb and index fingers at the midpoint of the arm." width="30%" />
<p class="caption">
Figure 5.1: Figure 1. Measurement of triceps skinfold using a Lange caliper. With the subject’s arm in a relaxed position, the skinfold is picked with thumb and index fingers at the midpoint of the arm.
</p>
</div>
<p><code>triceps</code> has nearly 30% missing values and <code>mass</code> has a few missing values. We can use the information in <code>mass</code> to impute the missing values in triceps - single imputation with a linear regression model. To perform imputation,</p>
<ol style="list-style-type: decimal">
<li><p>fit a linear regression model with <code>triceps</code> being the response and <code>mass</code> as the predictor.</p></li>
<li><p>use the above fitted regression to predict <code>triceps</code> on non-missing <code>mass</code>.</p></li>
<li><p>impute the missing value in <code>triceps</code> with the <em>predicted</em> <code>triceps</code>.</p></li>
</ol>
<p>Note that in R, records with missing components will be automatically deleted in the modeling process.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="eda-for-feature-engineering.html#cb72-1" tabindex="-1"></a>impute.lm <span class="ot">=</span> <span class="fu">lm</span>(triceps[<span class="sc">-</span><span class="dv">580</span>] <span class="sc">~</span> mass[<span class="sc">-</span><span class="dv">580</span>], <span class="at">data =</span> PimaDiabetes)</span>
<span id="cb72-2"><a href="eda-for-feature-engineering.html#cb72-2" tabindex="-1"></a><span class="fu">summary</span>(impute.lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = triceps[-580] ~ mass[-580], data = PimaDiabetes)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -19.6294  -4.9225  -0.4862   5.0930  21.3029 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -3.34070    1.56901  -2.129   0.0337 *  
## mass[-580]   0.98464    0.04669  21.087   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.442 on 536 degrees of freedom
##   (因为不存在，229个观察量被删除了)
## Multiple R-squared:  0.4534, Adjusted R-squared:  0.4524 
## F-statistic: 444.7 on 1 and 536 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="eda-for-feature-engineering.html#cb74-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb74-2"><a href="eda-for-feature-engineering.html#cb74-2" tabindex="-1"></a><span class="fu">plot</span>(impute.lm)</span></code></pre></div>
<p><img src="STA551EB_files/figure-html/unnamed-chunk-59-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The above fitted regression line will be used to <strong>impute</strong> the missing values in <code>triceps</code> in the following.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="eda-for-feature-engineering.html#cb75-1" tabindex="-1"></a>mass <span class="ot">=</span> PimaDiabetes<span class="sc">$</span>mass</span>
<span id="cb75-2"><a href="eda-for-feature-engineering.html#cb75-2" tabindex="-1"></a>impute.triceps <span class="ot">=</span> PimaDiabetes<span class="sc">$</span>triceps</span>
<span id="cb75-3"><a href="eda-for-feature-engineering.html#cb75-3" tabindex="-1"></a>n<span class="ot">=</span><span class="fu">length</span>(impute.triceps)</span>
<span id="cb75-4"><a href="eda-for-feature-engineering.html#cb75-4" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n){</span>
<span id="cb75-5"><a href="eda-for-feature-engineering.html#cb75-5" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.na</span>(impute.triceps[i]) <span class="sc">==</span> <span class="cn">TRUE</span> <span class="sc">&amp;&amp;</span> <span class="fu">is.na</span>(mass[i]) <span class="sc">==</span> <span class="cn">FALSE</span>) impute.triceps[i] <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">coef</span>(impute.lm)<span class="sc">*</span><span class="fu">c</span>(<span class="dv">1</span>,mass[i])) <span class="sc">+</span> <span class="fu">sample</span>(<span class="fu">resid</span>(impute.lm),<span class="dv">1</span>)</span>
<span id="cb75-6"><a href="eda-for-feature-engineering.html#cb75-6" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="eda-for-feature-engineering.html#cb76-1" tabindex="-1"></a>PimaDiabetes<span class="sc">$</span>impute.triceps <span class="ot">=</span> impute.triceps</span></code></pre></div>
<p>Next, we check whether the missing values in <code>triceps</code> were appropriately imputed.</p>
<p>We look at the density curves of <code>impute.triceps</code> and the original <code>triceps</code> to see the performance of the imputation and whether a discretization is needed.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="eda-for-feature-engineering.html#cb77-1" tabindex="-1"></a>den.tri <span class="ot">=</span> <span class="fu">density</span>(<span class="fu">na.omit</span>(PimaDiabetes<span class="sc">$</span>triceps))</span>
<span id="cb77-2"><a href="eda-for-feature-engineering.html#cb77-2" tabindex="-1"></a>den.imput.tri <span class="ot">=</span> <span class="fu">density</span>(<span class="fu">na.omit</span>(PimaDiabetes<span class="sc">$</span>impute.triceps))</span>
<span id="cb77-3"><a href="eda-for-feature-engineering.html#cb77-3" tabindex="-1"></a><span class="fu">plot</span>(den.imput.tri, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;triceps&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;density&quot;</span>, <span class="at">main =</span> <span class="st">&quot;original triceps vs imputed triceps&quot;</span>)</span>
<span id="cb77-4"><a href="eda-for-feature-engineering.html#cb77-4" tabindex="-1"></a><span class="fu">lines</span>(den.tri, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span>
<span id="cb77-5"><a href="eda-for-feature-engineering.html#cb77-5" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="fu">c</span>(<span class="st">&quot;Inputed Triceps&quot;</span>, <span class="st">&quot;Original Triceps&quot;</span>), <span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>), <span class="at">lty =</span><span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">bty=</span><span class="st">&quot;n&quot;</span>, <span class="at">cex =</span> <span class="fl">0.8</span>)</span></code></pre></div>
<p><img src="STA551EB_files/figure-html/unnamed-chunk-62-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>The above density curves indicate that</p>
<ul>
<li><p>the two distributions are almost identical, and</p></li>
<li><p>both distributions are almost symmetric (except for one outlier in the original data).</p></li>
</ul>
<p>Since the missing values in <code>triceps</code> were appropriately imputed, we next add the <code>impute.triceps</code> to the original data frame and drop the original <code>triceps</code>.</p>
<p>To close this imputation section, we re-organize the data set by dropping the original variables and keeping the imputed variables. At the same time, we also delete all records with missing components.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="eda-for-feature-engineering.html#cb78-1" tabindex="-1"></a>PimaDiabetes <span class="ot">=</span> <span class="fu">na.omit</span>(PimaDiabetes[, <span class="fu">c</span>(<span class="st">&quot;pregnant&quot;</span>, <span class="st">&quot;glucose&quot;</span>, <span class="st">&quot;pressure&quot;</span>, <span class="st">&quot;mass&quot;</span> , <span class="st">&quot;pedigree&quot;</span> , <span class="st">&quot;age&quot;</span> ,<span class="st">&quot;impute.log.insulin&quot;</span>, <span class="st">&quot;impute.triceps&quot;</span>, <span class="st">&quot;diabetes&quot;</span>)])</span></code></pre></div>
<p><br />
</p>
</div>
</div>
<div id="assess-distributions" class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Assess Distributions<a href="eda-for-feature-engineering.html#assess-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This subsection focuses on the potential discretization of continuous variables and grouping sparse categories of category variables based on their distribution.</p>
<div id="discretizing-continuous-variables" class="section level4 hasAnchor" number="5.2.2.1">
<h4><span class="header-section-number">5.2.2.1</span> Discretizing Continuous Variables<a href="eda-for-feature-engineering.html#discretizing-continuous-variables" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The above pairwise scatter plot shows that <code>glucose</code>, <code>pressure</code>(diastolic reading), and <code>age</code> are usually discretized in the clinical study. We will use the clinical standard and practices to discretize these variables</p>
<p>According to Medical News Today (<a href="https://www.medicalnewstoday.com/articles/a1c-chart-diabetes-numbers#a-1-c-chart" class="uri">https://www.medicalnewstoday.com/articles/a1c-chart-diabetes-numbers#a-1-c-chart</a>). The glucose levels <span class="math inline">\(&lt; 117\)</span>, <span class="math inline">\([117, 137]\)</span>, <span class="math inline">\(&gt;137\)</span> indicate normal, pre-diabetes, and diabetes.</p>
<p>According to National Diabetes Statistics Report (
<a href="https://www.cdc.gov/media/releases/2017/p0718-diabetes-report.html#:~:text=Rates%20of%20diagnosed%20diabetes%20increased,older%2C%2025%20percent%20had%20diabetes" class="uri">https://www.cdc.gov/media/releases/2017/p0718-diabetes-report.html#:~:text=Rates%20of%20diagnosed%20diabetes%20increased,older%2C%2025%20percent%20had%20diabetes</a>), rates of diagnosed diabetes increased with age. Among adults ages 18-44, 4 percent had diabetes. Among those ages 45-64 years, 17 percent had diabetes. And among those ages 65 years and older, 25 percent had diabetes.</p>
<p>According to The Seventh Report of the Joint National Committee on Prevention, Detection, Evaluation, and Treatment of High Blood Pressure (2003 Guideline, <a href="https://www.nhlbi.nih.gov/files/docs/guidelines/express.pdf" class="uri">https://www.nhlbi.nih.gov/files/docs/guidelines/express.pdf</a>), The normal diastolic pressure is less than 80 mm Hg, at risk diastolic reading is between 80 mm Hg and 90 mm Hg, abnormal (hypertension) diastolic reading is higher than 90 mm Hg.</p>
<p>We will discretize these three variables for future models and algorithms.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="eda-for-feature-engineering.html#cb79-1" tabindex="-1"></a>PimaDiabetes<span class="sc">$</span>grp.glucose <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(PimaDiabetes<span class="sc">$</span>glucose <span class="sc">&lt;</span> <span class="dv">117</span>, <span class="st">&#39;(0, 117)&#39;</span>,</span>
<span id="cb79-2"><a href="eda-for-feature-engineering.html#cb79-2" tabindex="-1"></a>               <span class="fu">ifelse</span>(PimaDiabetes<span class="sc">$</span>glucose <span class="sc">&gt;</span> <span class="dv">137</span>, <span class="st">&#39;&gt; 137&#39;</span>, <span class="st">&#39;[117,137]&#39;</span>))</span>
<span id="cb79-3"><a href="eda-for-feature-engineering.html#cb79-3" tabindex="-1"></a></span>
<span id="cb79-4"><a href="eda-for-feature-engineering.html#cb79-4" tabindex="-1"></a>PimaDiabetes<span class="sc">$</span>grp.diastolic <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(PimaDiabetes<span class="sc">$</span>pressure <span class="sc">&lt;</span> <span class="dv">80</span>, <span class="st">&#39;(0, 80)&#39;</span>,</span>
<span id="cb79-5"><a href="eda-for-feature-engineering.html#cb79-5" tabindex="-1"></a>               <span class="fu">ifelse</span>(PimaDiabetes<span class="sc">$</span>pressure <span class="sc">&gt;</span> <span class="dv">90</span>, <span class="st">&#39;&gt; 90&#39;</span>, <span class="st">&#39;[80,90]&#39;</span>))</span>
<span id="cb79-6"><a href="eda-for-feature-engineering.html#cb79-6" tabindex="-1"></a></span>
<span id="cb79-7"><a href="eda-for-feature-engineering.html#cb79-7" tabindex="-1"></a>PimaDiabetes<span class="sc">$</span>grp.age <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(PimaDiabetes<span class="sc">$</span>age <span class="sc">&lt;=</span> <span class="dv">44</span>, <span class="st">&#39;[21, 44]&#39;</span>,</span>
<span id="cb79-8"><a href="eda-for-feature-engineering.html#cb79-8" tabindex="-1"></a>               <span class="fu">ifelse</span>(PimaDiabetes<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">65</span>, <span class="st">&#39;65+&#39;</span>, <span class="st">&#39;[45, 64]&#39;</span>))</span></code></pre></div>
<p><br />
</p>
</div>
<div id="grouping-sparse-categories" class="section level4 hasAnchor" number="5.2.2.2">
<h4><span class="header-section-number">5.2.2.2</span> Grouping Sparse Categories<a href="eda-for-feature-engineering.html#grouping-sparse-categories" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The number of times pregnant <code>pregnant</code> is a discrete numerical variable. We could also consider it as an ordinal categorical variable.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="eda-for-feature-engineering.html#cb80-1" tabindex="-1"></a>pregnancy <span class="ot">=</span> <span class="fu">table</span>(PimaDiabetes<span class="sc">$</span>pregnant)</span>
<span id="cb80-2"><a href="eda-for-feature-engineering.html#cb80-2" tabindex="-1"></a><span class="fu">barplot</span>(pregnancy, <span class="at">main =</span> <span class="st">&quot;Distribution of pregnacies&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Pregnant Times&quot;</span>)</span></code></pre></div>
<p><img src="STA551EB_files/figure-html/unnamed-chunk-65-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>There are a few sparse categories in the variable, we decide to group this variable in the following:
0, 1, 2, 3-4, 5-7, 8+.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="eda-for-feature-engineering.html#cb81-1" tabindex="-1"></a>PimaDiabetes<span class="sc">$</span>grp.pregnant <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(PimaDiabetes<span class="sc">$</span>pregnant <span class="sc">==</span> <span class="dv">0</span>, <span class="st">&#39;0&#39;</span>,</span>
<span id="cb81-2"><a href="eda-for-feature-engineering.html#cb81-2" tabindex="-1"></a>                                <span class="fu">ifelse</span>(PimaDiabetes<span class="sc">$</span>pregnant <span class="sc">==</span> <span class="dv">1</span>, <span class="st">&#39;1&#39;</span>, </span>
<span id="cb81-3"><a href="eda-for-feature-engineering.html#cb81-3" tabindex="-1"></a>                                   <span class="fu">ifelse</span>(PimaDiabetes<span class="sc">$</span>pregnant <span class="sc">==</span> <span class="dv">2</span>, <span class="st">&#39;2&#39;</span>,</span>
<span id="cb81-4"><a href="eda-for-feature-engineering.html#cb81-4" tabindex="-1"></a>                                      <span class="fu">ifelse</span>((PimaDiabetes<span class="sc">$</span>pregnant <span class="sc">==</span> <span class="dv">3</span> <span class="sc">|</span> PimaDiabetes<span class="sc">$</span>pregnant <span class="sc">==</span> <span class="dv">4</span>), <span class="st">&#39;3-4&#39;</span>,</span>
<span id="cb81-5"><a href="eda-for-feature-engineering.html#cb81-5" tabindex="-1"></a>                                         <span class="fu">ifelse</span>((PimaDiabetes<span class="sc">$</span>pregnant <span class="sc">==</span> <span class="dv">5</span> <span class="sc">|</span> PimaDiabetes<span class="sc">$</span>pregnant <span class="sc">==</span> <span class="dv">6</span> <span class="sc">|</span> PimaDiabetes<span class="sc">$</span>pregnant <span class="sc">==</span> <span class="dv">7</span>), <span class="st">&#39;5-7&#39;</span>, </span>
<span id="cb81-6"><a href="eda-for-feature-engineering.html#cb81-6" tabindex="-1"></a>                                            <span class="fu">ifelse</span>(PimaDiabetes<span class="sc">$</span>pregnant <span class="sc">&gt;=</span> <span class="dv">8</span>, <span class="st">&#39;8+&#39;</span>, <span class="st">&quot;NA&quot;</span>))))))</span></code></pre></div>
<p>As the last step, we only keep those variables to used in the subsequent modeling.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="eda-for-feature-engineering.html#cb82-1" tabindex="-1"></a>var.names <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mass&quot;</span>, <span class="st">&quot;pedigree&quot;</span>, <span class="st">&quot;impute.log.insulin&quot;</span>, <span class="st">&quot;impute.triceps&quot;</span>, <span class="st">&quot;grp.glucose&quot;</span>, <span class="st">&quot;grp.diastolic&quot;</span>, <span class="st">&quot;grp.age&quot;</span>, <span class="st">&quot;grp.pregnant&quot;</span>, <span class="st">&quot;diabetes&quot;</span>) </span>
<span id="cb82-2"><a href="eda-for-feature-engineering.html#cb82-2" tabindex="-1"></a>PimaDiabetes <span class="ot">=</span> PimaDiabetes[, var.names]</span></code></pre></div>
</div>
<div id="save-analytic-dataset" class="section level4 hasAnchor" number="5.2.2.3">
<h4><span class="header-section-number">5.2.2.3</span> Save Analytic Dataset<a href="eda-for-feature-engineering.html#save-analytic-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The final analytic data should be saved as a permanent data for the subsequent analysis and modeling and upload the saved data set to HitHub data repository for an easy access in the future.</p>
<pre><code>write.csv(PimaDiabetes, &quot;C:\\Users\\75CPENG\\OneDrive - West Chester University of PA\\Desktop\\cpeng\\WCU-Teaching\\2023Summer\\STA551\\w03\\AnalyticPimaDiabetes.csv&quot;)</code></pre>
<p>The above csv file is also uploaded to the GitHub data repository at <a href="https://pengdsci.github.io/STA551/w03/AnalyticPimaDiabetes.csv" class="uri">https://pengdsci.github.io/STA551/w03/AnalyticPimaDiabetes.csv</a>.</p>
</div>
</div>
<div id="pairwise-association" class="section level3 hasAnchor" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> Pairwise Association<a href="eda-for-feature-engineering.html#pairwise-association" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Depending on the types of variables, there are three different combinations of two variables: two numeric variables, two categorical variables, one numeric variable, and one categorical variable. We will assess the association between two variables graphically based on the above three scenarios.</p>
<div id="two-numeric-variables-1" class="section level4 hasAnchor" number="5.2.3.1">
<h4><span class="header-section-number">5.2.3.1</span> Two Numeric Variables<a href="eda-for-feature-engineering.html#two-numeric-variables-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The best visual tool for assessing pairwise linear association between two numeric variables is a pair-wise scatter plot. The pair-wise scatter plot and its variants are available in several different R packages.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="eda-for-feature-engineering.html#cb84-1" tabindex="-1"></a><span class="fu">ggpairs</span>(PimaDiabetes,                  <span class="co"># Data frame</span></span>
<span id="cb84-2"><a href="eda-for-feature-engineering.html#cb84-2" tabindex="-1"></a>        <span class="at">columns =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,         <span class="co"># Columns</span></span>
<span id="cb84-3"><a href="eda-for-feature-engineering.html#cb84-3" tabindex="-1"></a>        <span class="fu">aes</span>(<span class="at">color =</span> diabetes,  <span class="co"># Color by group (cat. variable)</span></span>
<span id="cb84-4"><a href="eda-for-feature-engineering.html#cb84-4" tabindex="-1"></a>            <span class="at">alpha =</span> <span class="fl">0.5</span>))      <span class="co"># Transparency</span></span></code></pre></div>
<pre><code>## plot: [1,1] [====&gt;----------------------------------------------------------------------------------] 6% est: 0s
## plot: [1,2] [==========&gt;----------------------------------------------------------------------------] 12% est: 0s
## plot: [1,3] [===============&gt;-----------------------------------------------------------------------] 19% est: 1s
## plot: [1,4] [=====================&gt;-----------------------------------------------------------------] 25% est: 1s
## plot: [2,1] [==========================&gt;------------------------------------------------------------] 31% est: 1s
## plot: [2,2] [================================&gt;------------------------------------------------------] 38% est: 0s
## plot: [2,3] [=====================================&gt;-------------------------------------------------] 44% est: 0s
## plot: [2,4] [===========================================&gt;-------------------------------------------] 50% est: 0s
## plot: [3,1] [================================================&gt;--------------------------------------] 56% est: 0s
## plot: [3,2] [=====================================================&gt;---------------------------------] 62% est: 0s
## plot: [3,3] [===========================================================&gt;---------------------------] 69% est: 0s
## plot: [3,4] [================================================================&gt;----------------------] 75% est: 0s
## plot: [4,1] [======================================================================&gt;----------------] 81% est: 0s
## plot: [4,2] [===========================================================================&gt;-----------] 88% est: 0s
## plot: [4,3] [=================================================================================&gt;-----] 94% est: 0s
## plot: [4,4] [=======================================================================================]100% est: 0s</code></pre>
<p><img src="STA551EB_files/figure-html/unnamed-chunk-68-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>The off-diagonal plots and numbers indicate the correlation between the pair-wise numeric variables. As expected, triceps and mass are significantly correlated. Other paired variables have weak correlations.</p>
<p>The main diagonal stacked density curves show the potential difference in the distribution of the underlying numeric variable in diabetes and diabetes-free groups. This means that the stacked density curves show the relation between numeric and categorical variables. These stacked density curves are not completely overlapped indicating somewhat correlation between each of these numeric variables and the binary response variable.</p>
<p>Because of the above interpretation between numeric variables and the binary response variable, we will not open a new subsection to illustrate the relationship between a numeric variable and a categorical variable.</p>
<p><br />
</p>
</div>
<div id="two-categorical-variables" class="section level4 hasAnchor" number="5.2.3.2">
<h4><span class="header-section-number">5.2.3.2</span> Two Categorical Variables<a href="eda-for-feature-engineering.html#two-categorical-variables" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Mosaic plots are convenient to show whether two categorical variables are dependent. In EDA, we are primarily interested in whether the response (binary in this case) is independent of categorical variables. Those categorical variables that are independent of the response variable should be excluded in any of the subsequent models and algorithms.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="eda-for-feature-engineering.html#cb86-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb86-2"><a href="eda-for-feature-engineering.html#cb86-2" tabindex="-1"></a><span class="fu">mosaicplot</span>(grp.glucose <span class="sc">~</span> diabetes, <span class="at">data=</span>PimaDiabetes,<span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;Blue&quot;</span>,<span class="st">&quot;Red&quot;</span>), <span class="at">main=</span><span class="st">&quot;glucose vs diabetes&quot;</span>)</span>
<span id="cb86-3"><a href="eda-for-feature-engineering.html#cb86-3" tabindex="-1"></a><span class="fu">mosaicplot</span>(grp.diastolic <span class="sc">~</span> diabetes, <span class="at">data=</span>PimaDiabetes,<span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;Blue&quot;</span>,<span class="st">&quot;Red&quot;</span>), <span class="at">main=</span><span class="st">&quot;diastolic vs diabetes&quot;</span>)</span>
<span id="cb86-4"><a href="eda-for-feature-engineering.html#cb86-4" tabindex="-1"></a><span class="fu">mosaicplot</span>(grp.age <span class="sc">~</span> diabetes, <span class="at">data=</span>PimaDiabetes,<span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;Blue&quot;</span>,<span class="st">&quot;Red&quot;</span>), <span class="at">main=</span><span class="st">&quot;age vs diabetes&quot;</span>)</span>
<span id="cb86-5"><a href="eda-for-feature-engineering.html#cb86-5" tabindex="-1"></a><span class="fu">mosaicplot</span>(grp.pregnant <span class="sc">~</span> diabetes, <span class="at">data=</span>PimaDiabetes,<span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;Blue&quot;</span>,<span class="st">&quot;Red&quot;</span>), <span class="at">main=</span><span class="st">&quot;pregnant vs diabetes&quot;</span>)</span></code></pre></div>
<p><img src="STA551EB_files/figure-html/unnamed-chunk-69-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>The top two mosaic plots demonstrate the positive association between <code>glucose</code> levels and <code>diastolic</code> readings. The bottom two mosaic plots also show that diabetes is not independent of <code>age</code> and <code>pregnant</code> times because the proportion of diabetes cases in individual categories is not identical.</p>
<p><br />
</p>
</div>
</div>
</div>
<div id="concluding-remarks" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Concluding Remarks<a href="eda-for-feature-engineering.html#concluding-remarks" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="img03/BeginWithEndInMind.png" width="40%" style="display: block; margin: auto;" /></p>
<p><br />
</p>
<p>We <strong>begin</strong> with records that may have missing values and <strong>end</strong> up with an engineered record to be fed into models and algorithms!</p>
<p><img src="img03/productionRecord.png" width="95%" style="display: block; margin: auto;" /></p>
<p>However, if the incoming record has a missing value in mass, the resulting engineered record cannot be fed to the candidate models and algorithms since it has a missing value (most programs will automatically delete this record), hence, there will be no predicted value for the response!</p>
<p><img src="img03/PreMeanReplaceRecord.png" width="95%" style="display: block; margin: auto;" /></p>
<p>Therefore, we need a replacement imputation before any model-based imputation. This is practically important since it will prevent the potential failure of the dynamic prediction system!</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="exploratory-data-analysis-eda.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multiple-linear-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/pengdsci/STA551EB/edit/master/04-EDAforFeatureEngineering.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["STA551EB.pdf", "STA551EB.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
